print ("Tugas Python")
print ()
nama = input("masukan Nama Anda :")
pgln = input("masukan Panggilan :")
nim = input("masukan Nim :")
tglhr = input("masukan Tanggal Lahir :")
tmlhr = input("masukan Tempat Lahir :")
tlpn = input("masukan Telepon :")
almt = input("masukan Alamat :")
umur = input("masukan Umur Anda :")
print ()
print ("Assalamua'laikum")
print ()
print ("Let me introduce my self.my name is",nama,"but you can call me",pgln,"My NIM is",nim,"I was born in",tmlhr,"and I am",umur,"years old. i am very gald if you want to invite my house in",almt,".So,don't forget to call me before with the number",tlpn,)
print ()
print ("THANK YOU")
